create table books (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    rating INTEGER NOT NULL,
    author TEXT NOT NULL,
    genre TEXT NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
    owner INTEGER REFERENCES users(id)
)